# Generated by Django 4.2.6 on 2023-10-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('vin', models.CharField(max_length=17)),
                ('year', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sellerName', models.CharField(max_length=256)),
                ('sellerEmail', models.CharField(max_length=256)),
                ('sellerPhone', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=256)),
                ('userEmail', models.CharField(max_length=256)),
                ('userPhone', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('reviewID', models.CharField(auto_created=True, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=256)),
                ('sellerID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellerReview', to='storage.seller')),
                ('userID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userIDsReview', to='storage.user')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('requestID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('requestDate', models.DateField()),
                ('status', models.CharField(max_length=256)),
                ('carID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carIDsPurchase', to='storage.car')),
                ('userID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userIDsPurchase', to='storage.user')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('imageID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='car_image/')),
                ('imageURL', models.CharField(max_length=256)),
                ('carID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carIDs', to='storage.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='sellerID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='storage.seller'),
        ),
    ]
