# Generated by Django 4.2.6 on 2023-10-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='fileName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='reviewName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='carID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carImages', to='storage.car'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='file',
            field=models.FileField(null=True, upload_to='car_image/'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='imageURL',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='reviewID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
