# Generated by Django 4.2.6 on 2024-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_carimage_filename_sellerreview_reviewname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='sellerID',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='carID',
        ),
        migrations.AlterField(
            model_name='carimage',
            name='file',
            field=models.FileField(null=True, upload_to='storage/car_image/'),
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='userID',
        ),
        migrations.AddField(
            model_name='car',
            name='sellerID',
            field=models.ManyToManyField(null=True, related_name='seller', to='storage.seller'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='carID',
            field=models.ManyToManyField(null=True, related_name='carImages', to='storage.car'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='userID',
            field=models.ManyToManyField(null=True, related_name='userIDsPurchase', to='storage.user'),
        ),
    ]
