# Generated by Django 4.2.6 on 2024-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_car_sellerid_remove_carimage_carid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('partId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=256)),
                ('partPrice', models.IntegerField()),
                ('condition', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('sellerID', models.ManyToManyField(null=True, related_name='partSeller', to='storage.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('imageID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=256, null=True)),
                ('file', models.FileField(null=True, upload_to='storage/part_image/')),
                ('imageURL', models.CharField(max_length=256, null=True)),
                ('partID', models.ManyToManyField(null=True, related_name='partImages', to='storage.part')),
            ],
        ),
    ]
