# Generated by Django 4.2.6 on 2024-01-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_car_sellerid_alter_carimage_carid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='partId',
            new_name='partID',
        ),
    ]
