# Generated by Django 4.2.6 on 2024-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_rename_partid_part_partid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
