# Generated by Django 4.2.6 on 2024-01-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_seller_sellerpassword_user_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='carID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPassword',
        ),
    ]
