# Generated by Django 4.2.6 on 2024-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_carimage_carid_remove_user_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carImage',
            field=models.ManyToManyField(related_name='car_image', to='storage.carimage'),
        ),
    ]
