# Generated by Django 4.2.6 on 2024-01-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_car_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carImage',
        ),
        migrations.AddField(
            model_name='carimage',
            name='carID',
            field=models.ManyToManyField(related_name='carImages', to='storage.car'),
        ),
    ]
