# Generated by Django 4.2.6 on 2024-01-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_remove_car_carimage_carimage_carid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='carID',
        ),
        migrations.AddField(
            model_name='car',
            name='imageID',
            field=models.ManyToManyField(related_name='image', to='storage.carimage'),
        ),
    ]
