# Generated by Django 4.2.6 on 2024-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_remove_carimage_carid_car_imageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partimage',
            name='partID',
        ),
        migrations.AddField(
            model_name='part',
            name='partImageID',
            field=models.ManyToManyField(related_name='partImageID', to='storage.partimage'),
        ),
    ]
